### ISSUE TITLE
Show hint that file will be replaced

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.file#38]
It can be confusing for users when no hint is shown that file will be replaced.

**Comment by jone** [comment]
@shylux can you take care of that?

**Comment by shylux** [comment]
@bierik do you mean a hint on the quickupload drop zone?

**Comment by jone** [comment]
@shylux yes, exactl.y

Files can be uploaded in to a container (Workspace, for example) or into the file directly. But: when I drag the file into the workspace, it creates a new file, but when I drag it onto an existing file, the file is replaced. The user needs to be aware of this.

I think that the "replacing" drop-zope must have an adequate hint so that the user is aware that he's replacing the existing file.

**Comment by bierik** [comment]
@shylux I think the hint should be also visible before the user starts dragging a file. So I would suggest a orange colored text with a hint that the file will be replaced next to the mimetype icon and a hint on the dropzone as well.

![screen](https://cloud.githubusercontent.com/assets/1637820/7560263/c0972d26-f7c1-11e4-8324-7f09edb35346.jpg)

**Comment by bierik** [comment]
Fixed trough #44
